version: "3.9"
services:
  db:
    image: postgres:12
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=warsphered
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: tail -f /dev/null
    depends_on:
      - db
